clc;
clear;
rng default
figure(1)
rm1=mytree(8)
title('Poly1')
xlabel('data points')
ylabel('Poly1')
figure(2)
rm2=mytree(9)
title('Poly2')
xlabel('data points')
ylabel('Poly2')
figure(3)
rm3=mytree(10)
title('Poly3')
xlabel('data points')
ylabel('Poly3')
figure(4)
rm4=mytree(11)
title('Am')
xlabel('data points')
ylabel('Am')
figure(5)
rm5=mytree(12)
title('Mono')
xlabel('data points')
ylabel('Mono')